Add the feature to auto-scroll
emilioastarita/lyricfier pull request #68
Opened 2017-03-01 02:02 UTC by bruceshenzk

As a music lyric software, it is pretty inconvenient not having the feature to scroll down the lyric box automatically. I recorded the duration into the song object and used the window height and total scroll height as indicators to decide when to begin scrolling and what the interval should be for scroll down one px. 

This approach is not accurate but approximate because I assume the constant pace of the music lyrics. 

Hope you can add this to the settings of the program so that users can choose it.

2017-06-12 12:15 UTC, Jhony33 commented
Yes please. Please add scrolling feature. Thanks. :)

2017-10-05 00:53 UTC, emilioastarita requested changes
Hello @bruceshenzk thanks for your PR. I need some changes to merge this. Could you please work on my comments? If you need any help please let me know. And sorry for the delay.

2017-10-05 00:53 UTC, emilioastarita commented on lyricfier.iml
> +<?xml version="1.0" encoding="UTF-8"?>
please remove this file.

2017-10-05 00:53 UTC, emilioastarita commented on render/Searcher.ts
> -
not relevant to the PR

2017-10-05 00:53 UTC, emilioastarita commented on render/SongRender.ts
> +                            document.getElementById("lyricBox").scrollTop = 0;
could you move this logic to a new function? and only do the work if the setting is enabled.

2017-10-05 00:53 UTC, emilioastarita commented on render/SongRender.ts
> +                            var scrollHeight = document.getElementById("lyricBox").scrollHeight;
use `const` or `let` to declare local vars.

2017-10-05 00:53 UTC, emilioastarita commented on render/SongRender.ts
> +    pageScroll(aSong, i, s) {
please rename this vars with better names.

2017-10-05 00:53 UTC, emilioastarita commented on render/SpotifyService.ts
> +        console.log("========");
remove this

2017-10-06 21:52 UTC, bruceshenzk commented
Hi, @emilioastarita . Please review the changes.

2017-10-06 22:15 UTC, emilioastarita approved these changes

2017-10-06 22:15 UTC, merged